/**
 * `verifactu schema` subcommand — emit a Drizzle table definition for the
 * hash-chain `HashStore` adapters (`verifactu-sdk/store/drizzle`) into the
 * caller's own schema directory.
 *
 * The generated file is a starting point, not a managed artifact: once
 * written it belongs to the caller's own schema and drizzle-kit migrations,
 * exactly like `DrizzlePgHashStore`/`DrizzleMysqlHashStore`/
 * `DrizzleSqliteHashStore` expect (see `src/store/adapters/drizzle.ts`).
 *
 * @module
 */

import { access, mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { type Command, Option } from 'commander';
import { errorBanner, successBanner } from '../ux.js';

/** Dialects the `schema drizzle` subcommand can emit a table for. */
type DrizzleProvider = 'pg' | 'mysql' | 'sqlite';

/**
 * Render the Drizzle table source for the given provider.
 *
 * The three required columns (`nif`, `invoiceId`, `hash`) match
 * {@link file://../../store/adapters/drizzle.ts | PgHashChainColumns} and its
 * MySQL/SQLite counterparts byte-for-byte — do not rename them without also
 * updating the adapter's expected column shape.
 *
 * @param provider - Target Drizzle dialect.
 * @param tableName - SQL table name to generate (defaults to
 *   `verifactu_hash_chain`, matching every other bundled adapter).
 */
function renderSchema(provider: DrizzleProvider, tableName: string): string {
  const header = `/**\n * Drizzle table for verifactu-sdk's hash-chain HashStore.\n *\n * Generated by \`bunx verifactu schema drizzle --provider ${provider}\`.\n * This file is yours now — fold it into your own schema, run it through\n * drizzle-kit, and pass the exported table into Drizzle${
    provider === 'pg' ? 'Pg' : provider === 'mysql' ? 'Mysql' : 'Sqlite'
  }HashStore.\n */\n\n`;

  if (provider === 'pg') {
    return `${header}import { pgTable, text } from 'drizzle-orm/pg-core';

export const verifactuHashChain = pgTable('${tableName}', {
  nif: text('nif').primaryKey(),
  invoiceId: text('invoice_id').notNull(),
  hash: text('hash').notNull(),
});
`;
  }

  if (provider === 'mysql') {
    return `${header}import { mysqlTable, varchar } from 'drizzle-orm/mysql-core';

export const verifactuHashChain = mysqlTable('${tableName}', {
  nif: varchar('nif', { length: 255 }).primaryKey(),
  invoiceId: varchar('invoice_id', { length: 2048 }).notNull(),
  hash: varchar('hash', { length: 64 }).notNull(),
});
`;
  }

  return `${header}import { sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const verifactuHashChain = sqliteTable('${tableName}', {
  nif: text('nif').primaryKey(),
  invoiceId: text('invoice_id').notNull(),
  hash: text('hash').notNull(),
});
`;
}

/**
 * Build the `schema` `Command` definition and attach it to the root
 * commander instance.
 *
 * @param program - The root `Command` from `src/cli/bin.ts`.
 * @returns The same `Command` to enable fluent chaining.
 */
export function registerSchemaCommand(program: Command): Command {
  const schema = program
    .command('schema')
    .description('Generate schema files for HashStore adapters');

  schema
    .command('drizzle')
    .description(
      'Emit a Drizzle table for the DrizzlePgHashStore/DrizzleMysqlHashStore/DrizzleSqliteHashStore adapters',
    )
    .addOption(
      new Option('--provider <provider>', 'Target Drizzle dialect')
        .choices(['pg', 'mysql', 'sqlite'])
        .makeOptionMandatory(true),
    )
    .option(
      '--out <path>',
      'File to write (the schema route in your project)',
      './verifactu-schema.ts',
    )
    .option('--table-name <name>', 'SQL table name to generate', 'verifactu_hash_chain')
    .option('--force', 'Overwrite the output file if it already exists', false)
    .action(async (opts: Record<string, unknown>) => {
      try {
        const provider = opts.provider as DrizzleProvider;
        const outPath = String(opts.out);
        const tableName = String(opts.tableName);
        const force = Boolean(opts.force);

        if (!force) {
          const exists = await access(outPath)
            .then(() => true)
            .catch(() => false);
          if (exists) {
            throw new Error(`'${outPath}' already exists — pass --force to overwrite it`);
          }
        }

        await mkdir(dirname(outPath), { recursive: true });
        await writeFile(outPath, renderSchema(provider, tableName), 'utf8');
        successBanner(`Drizzle (${provider}) schema written to ${outPath}`);
      } catch (error) {
        errorBanner('Schema generation failed', error);
        process.exitCode = 1;
      }
    });

  return schema;
}
